local paths = require("dock.system.paths")

local M = {}

local function ok(data) return { ok = true, data = data } end
local function err(message, code) return { ok = false, error = tostring(message), code = code or "STUDIO_ERROR" } end

local function safe_id(value)
  value = tostring(value or "my_app"):lower():gsub("[^%w_%-%.]", "_")
  value = value:gsub("^_+", ""):gsub("_+$", "")
  if value == "" then value = "my_app" end
  if not value:find(".", 1, true) then value = "user." .. value end
  return value
end

local function safe_file_name(value)
  value = tostring(value or "Paralimni App"):gsub("[/\\:%*%?\"<>|]", "")
  value = value:gsub("^%s+", ""):gsub("%s+$", ""):gsub("%s+", " ")
  if value == "" then value = "Paralimni App" end
  return value
end

local function escape_lua(value)
  return string.format("%q", tostring(value or ""))
end

local function encode_manifest(project)
  local permissions = {}
  for _, permission in ipairs(project.permissions or {}) do table.insert(permissions, '"' .. permission .. '"') end
  return "{\n" ..
    '  "id": "' .. project.id .. '",\n' ..
    '  "name": "' .. project.name .. '",\n' ..
    '  "version": "' .. (project.version or "0.0.1") .. '",\n' ..
    '  "entry": "main.lua",\n' ..
    '  "type": "user",\n' ..
    '  "category": "created",\n' ..
    '  "icon": "' .. (project.icon or "placeholder") .. '",\n' ..
    '  "permissions": [' .. table.concat(permissions, ", ") .. '],\n' ..
    '  "file_associations": [],\n' ..
    '  "autoload": false,\n' ..
    '  "desktop": true\n' ..
    "}\n"
end

local function render_main(project)
  local lines = {
    "-- Generated by DockOS App Studio",
    "return {",
    "  run = function(ctx)",
    "    local app_name = " .. escape_lua(project.name),
    "    ctx.ui.menu.set({",
    "      { id = \"app.about\", label = \"About\" },",
    "      { id = \"app.reload\", label = \"Reload\" },",
    "    })",
    "    ctx.notification.send(app_name, \"Application started\")",
    "    while true do",
    "      local event, payload = coroutine.yield(\"*\")",
    "      if event == \"dock_app_event\" and type(payload) == \"table\" and payload.app_id == ctx.app.id then",
    "        if payload.kind == \"button\" and payload.action == \"notify\" then",
    "          ctx.notification.send(app_name, payload.message or \"Button pressed\")",
    "        end",
    "      elseif event == \"terminate\" then",
    "        break",
    "      end",
    "    end",
    "    return { ok = true }",
    "  end,",
    "}",
  }
  return table.concat(lines, "\n") .. "\n"
end

function M.new(ctx)
  local service = { ctx = ctx, project = nil }
  local projects_dir = paths.join(paths.userFolder("default", "Apps"), "StudioProjects")

  local function ensure()
    if not fs.exists(projects_dir) then fs.makeDir(projects_dir) end
  end

  local function default_project()
    local project = {
      id = "user.paralimni_app",
      name = "Paralimni App",
      version = "0.0.1",
      icon = "placeholder",
      permissions = { "fs.read", "notification.send", "settings.read", "settings.write" },
      window = { w = 220, h = 120 },
      preview_scroll_x = 0,
      preview_scroll_y = 0,
      components = {
        { kind = "text", text = "Hello from DockOS", x = 12, y = 12, w = 92, h = 14 },
        { kind = "button", label = "Notify", action = "notify", message = "Hello from App Studio", x = 12, y = 34, w = 62, h = 16 },
      },
      code = "",
      selected = 1,
      dirty = false,
    }
    project.code = render_main(project)
    return project
  end

  function service.current()
    if not service.project then service.project = default_project() end
    return ok(service.project)
  end

  function service.newProject(name)
    service.project = default_project()
    if name and name ~= "" then
      service.project.name = tostring(name)
      service.project.id = safe_id(name)
    end
    service.project.code = render_main(service.project)
    service.project.dirty = true
    return ok(service.project)
  end

  function service.addComponent(kind)
    local project = service.current().data
    kind = tostring(kind or "text")
    local component = { kind = kind, x = 16 + (#project.components * 6), y = 16 + (#project.components * 5), w = 70, h = 16 }
    if kind == "text" then component.text = "Text"
    elseif kind == "input" then component.label = "Text Input"; component.w = 86
    elseif kind == "image" then component.label = "Image"; component.w = 54; component.h = 34
    elseif kind == "shape" then component.label = "Shape"; component.w = 72; component.h = 38
    else component.label = "Button"; component.action = "notify"; component.message = "Button pressed"; component.kind = "button" end
    table.insert(project.components, component)
    project.selected = #project.components
    project.code = render_main(project)
    project.dirty = true
    return ok(component)
  end

  function service.selectComponent(index)
    local project = service.current().data
    index = tonumber(index)
    if not index or not project.components[index] then return err("component not found", "NOT_FOUND") end
    project.selected = index
    return ok(project.components[index])
  end

  function service.moveComponent(index, x, y)
    local project = service.current().data
    index = tonumber(index)
    local component = index and project.components[index]
    if not component then return err("component not found", "NOT_FOUND") end
    local window = project.window or { w = 220, h = 120 }
    component.x = math.max(1, math.min((window.w or 220) - math.max(12, component.w or 40), math.floor(tonumber(x) or component.x or 1)))
    component.y = math.max(1, math.min((window.h or 120) - 22 - math.max(8, component.h or 12), math.floor(tonumber(y) or component.y or 1)))
    project.selected = index
    project.code = render_main(project)
    project.dirty = true
    return ok(component)
  end

  function service.scrollPreview(dx, dy)
    local project = service.current().data
    project.preview_scroll_x = math.max(0, (tonumber(project.preview_scroll_x) or 0) + (tonumber(dx) or 0))
    project.preview_scroll_y = math.max(0, (tonumber(project.preview_scroll_y) or 0) + (tonumber(dy) or 0))
    return ok({ x = project.preview_scroll_x, y = project.preview_scroll_y })
  end

  function service.sourceCode()
    local project = service.current().data
    project.code = render_main(project)
    return ok(project.code)
  end

  function service.loadExample(name)
    service.project = default_project()
    local project = service.project
    name = tostring(name or "notify")
    if name == "counter" then
      project.name = "Counter App"
      project.id = safe_id(project.name)
      project.components = {
        { kind = "text", text = "Counter", x = 14, y = 14, w = 70, h = 12 },
        { kind = "button", label = "Increment", action = "notify", message = "Counter clicked", x = 14, y = 34, w = 78, h = 16 },
        { kind = "shape", label = "Panel", x = 108, y = 16, w = 70, h = 54 },
      }
    else
      project.name = "Notification App"
      project.id = safe_id(project.name)
      project.components = {
        { kind = "text", text = "Notification demo", x = 14, y = 14, w = 112, h = 12 },
        { kind = "button", label = "Send", action = "notify", message = "Notification API works", x = 14, y = 36, w = 58, h = 16 },
        { kind = "input", label = "Message", x = 14, y = 60, w = 104, h = 16 },
      }
    end
    project.selected = 1
    project.code = render_main(project)
    project.dirty = true
    return ok(project)
  end

  function service.setName(name)
    local project = service.current().data
    project.name = tostring(name or project.name)
    project.id = safe_id(project.name)
    project.code = render_main(project)
    project.dirty = true
    return ok(project)
  end

  function service.setCode(code)
    local project = service.current().data
    project.code = tostring(code or "")
    project.dirty = true
    return ok(project)
  end

  function service.setIcon(icon)
    local project = service.current().data
    project.icon = tostring(icon or "placeholder")
    project.dirty = true
    return ok(project)
  end

  function service.cycleIcon()
    local project = service.current().data
    local icons = { "placeholder", "studio", "settings", "folder", "terminal" }
    local current = project.icon or "placeholder"
    local next_icon = icons[1]
    for index, icon in ipairs(icons) do
      if icon == current then next_icon = icons[(index % #icons) + 1]; break end
    end
    return service.setIcon(next_icon)
  end

  function service.save()
    ensure()
    local project = service.current().data
    project.code = render_main(project)
    local path = paths.join(projects_dir, project.id .. ".json")
    project.dirty = false
    return ctx.safe_io.writeJson(path, project)
  end

  function service.exportApp()
    local project = service.current().data
    project.code = render_main(project)
    local target = paths.join(paths.userFolder("default", "Apps"), safe_file_name(project.name) .. ".app")
    if fs.exists(target) then fs.delete(target) end
    fs.makeDir(target)
    local manifest = ctx.safe_io.writeFile(paths.join(target, "app.json"), encode_manifest(project))
    if not manifest.ok then return manifest end
    local ui = ctx.safe_io.writeJson(paths.join(target, "ui.json"), {
      format = "dockos.app.ui",
      name = project.name,
      icon = project.icon or "placeholder",
      window = project.window or { w = 220, h = 120 },
      components = project.components or {},
    })
    if not ui.ok then return ui end
    local main = ctx.safe_io.writeFile(paths.join(target, "main.lua"), render_main(project))
    if not main.ok then return main end
    ctx.app_service.scanApps()
    if ctx.permission_service then
      for _, permission in ipairs(project.permissions or {}) do ctx.permission_service.grant(project.id, permission) end
    end
    project.dirty = false
    return ok({ path = target, manifest = paths.join(target, "app.json"), ui = paths.join(target, "ui.json") })
  end

  function service.preview()
    local project = service.current().data
    return ok({ title = project.name, components = project.components, window = project.window })
  end

  function service.start() return ok(true) end

  return service
end

return M
